const days={
"Fri 16":{title:"Palma arrival",items:[["Evening","Palma Old Town","Cathedral → old town → Santa Catalina / marina sunset. Keep it easy after the flight.","city","Sleep: Palma"],["Dinner","Palma","Relaxed dinner and early night before the north.","food",""]]},
"Sat 17":{title:"Forest → Lluc → Pollença",items:[["Morning","Caimari","Leave Palma and enter the foothills of the Tramuntana. Coffee / local stop.","drive","Route: Palma → Caimari"],["Late morning","Lluc","Monastery and pine forest. Short walk rather than a major hike.","nature","Route: Caimari → Lluc"],["Afternoon","Pollença","Old town, stone lanes and Calvari viewpoint.","village","Route: Lluc → Pollença"],["Evening","Pollença area","Check into a rural/agroturismo stay and dinner.","stay","Sleep: Pollença area"]]},
"Sun 18":{title:"Pollença → Formentor",items:[["Morning","Port de Pollença","Coast and slow breakfast / coffee.","sea","Route: Pollença → Port de Pollença"],["Midday","Formentor","Drive the dramatic peninsula; stop at Mirador des Colomer.","cliffs","Main scenic drive"],["Afternoon","Formentor Beach","Sea, pines and time to explore without rushing.","sea","Optional swim depending on conditions"],["Sunset","Formentor","Continue toward the lighthouse / sunset viewpoint if access and conditions allow.","sunset","Return to Pollença area"]]},
"Mon 19":{title:"Palma → airport",items:[["Morning","Palma","Breakfast, short old-town walk, then airport.","city","Flight: midday"]]}
};
const coords={Palma:[39.5696,2.6502],Caimari:[39.774,2.900],Lluc:[39.821,2.884],Pollença:[39.876,3.017],Port:[39.907,3.083],Formentor:[39.960,3.208]};
const map=L.map("map",{zoomControl:true}).setView([39.86,2.98],10);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);
Object.entries(coords).forEach(([n,c])=>L.marker(c).addTo(map).bindPopup("<b>"+n+"</b>"));
let line=L.polyline([coords.Palma,coords.Caimari,coords.Lluc,coords.Pollença,coords.Port,coords.Formentor],{weight:4}).addTo(map);
function render(k){document.querySelector("#days").innerHTML=Object.keys(days).map(x=>"<button class='"+(x===k?"active":"")+"' onclick='render(\""+x+"\")'>"+x+"</button>").join("");document.querySelector("#plan").innerHTML="<h2>"+days[k].title+"</h2>"+days[k].items.map(i=>"<article class='card'><div class='time'>"+i[0]+"</div><div class='title'>"+i[1]+"</div><div class='desc'>"+i[2]+"</div><span class='tag'>"+i[3]+"</span><div class='route'>"+i[4]+"</div></article>").join("");let pts=k==="Fri 16"?["Palma"]:k==="Sat 17"?["Palma","Caimari","Lluc","Pollença"]:k==="Sun 18"?["Pollença","Port","Formentor"]:["Palma"];map.fitBounds(L.latLngBounds(pts.map(x=>coords[x])),{padding:[60,60]})}render("Sat 17");